### ISSUE TITLE
Music

### ISSUE THREAD

**Issue by adamint** [ArdentDiscord/Ardent-2018#2]
For commands to start with, play, skip, resume, pause, fastforward, rewind, song (title + link, also alias of playing or np), queue, repeat, clearqueue, removefrom, volume. All should be written keeping in mind that playlist creation will be a feature in the future.

Queue should link to /:guildid/queue

**Comment by Mordo56** [comment]
I got you on this please hire me

**Comment by Mordo56** [comment]
I may can finally you using lavalink/lavaplayer  I wanna contribute/help on music and other things I know kotlin better now im mordo in DISCORD.

**Comment by adamint** [comment]
@RevNex As long as the code is production quality, I'm willing to accept the help. To run Ardent, you need to install Docker (and docker compose) and get familiar with both

**Comment by Mordo56** [comment]
ok.

**Comment by Mordo56** [comment]
@adamint when do plan to start music

**Comment by adamint** [comment]
no eta, but likely tomorrow. still working on website management endpoints

**Comment by RevNex** [comment]
change the playing status to streaming like v2 had
